### ISSUE TITLE
Emojis appears in Top 20 Words

### ISSUE THREAD

**Issue by Banalian** [davidbmaier/discord-recap#2]
While in a call with someone, they checked their package and found some emojis in their Top 20 Words.

I'm not sure that it is a correct behavior since there's the top 20 emojis/emotes

![Emojis in Top](https://user-images.githubusercontent.com/64379456/148702514-64ef1df2-e2a5-4679-b708-05f148ebf375.png)

**Comment by davidbmaier** [comment]
Ah fair, I'm only filtering out the Discord emoji - should be an easy fix.

**Comment by davidbmaier** [comment]
Fixed in https://github.com/davidbmaier/discord-recap/commit/89e2fd4252534b0268554aad93d4f5eb6bd8295f.
Should get filtered out now - you'll need to re-scan your package.
Bit annoying to test on my end but I think I got all edge cases.
Feel free to reopen if you can still reproduce it.
