### ISSUE TITLE
Error when processing a package without predicted age

### ISSUE THREAD

**Issue by LinUwUxCat** [davidbmaier/discord-recap#21]
If the package doesn't have a predicted age, which could happen by simply not having the `activity/analytics/events-[...].json` file (which happens because the user disabled "Use data to personalise my Discord experience" in privacy settings), then the page can't process the package file and the following error happens : 
```
TypeError: t.eventStats.predictedAge is undefined
    s1 https://www.discord-recap.com/build/routes/stats/index-TOLD66WT.js:13
    d1 https://www.discord-recap.com/build/routes/stats/index-TOLD66WT.js:13
    [Rest of the error omitted because most likely unrelevant]
```

**Comment by davidbmaier** [comment]
Ah good catch, forgot to test that. Will have a look, probably pretty simple fix.

**Comment by davidbmaier** [comment]
Should be fixed, can you check again? @LinUwUxCat 
Make sure you do a full refresh just in case.

**Comment by LinUwUxCat** [comment]
Yep, it works now! thanks
