### ISSUE TITLE
[Suggestion]Sort DMs by latest message?

### ISSUE THREAD

**Issue by TenguOnTheTop** [davidbmaier/discord-recap#22]
I dunno how easy this would be, but is it possible to have the option to sort your DMs by the latest message you've sent? 

 I'd find it useful if I'm trying to find old chats w/ someone, since Discord closes older DMs.

**Comment by davidbmaier** [comment]
Not sure off the top of my head, I'll have a look later.

**Comment by davidbmaier** [comment]
I've added some sorting features for the DM, server, server channel and global channel tables - should hopefully all work fine, I didn't have tons of time to test.
If you encounter any problems, make sure you go through the package analysis/scan again - and if that doesn't help feel free to reopen this issue and let me know about the details.
