### ISSUE TITLE
Package is missing required files

### ISSUE THREAD

**Issue by 71NX0** [davidbmaier/discord-recap#24]
I got the files and checked all boxes when requesting it yet when I uploaded the zip file it just told me this: 
Package is missing required file(s): events.json in /activity/reporting

I made sure 3 times to check all boxes so why doesnt it work?

**Comment by davidbmaier** [comment]
I think the first time I tried it I checked all boxes but Discord sent me an incomplete package anyway - not sure if anyone else had that same experience, but maybe that's what happened to you too.

Alternatively it's possible they've changed the file name's format/structure and I'll need to update the site. 
If you unpack the package zip yourself and look inside, can you take a screenshot of the content of the folder in the error (`/activity/reporting/`)? It won't contain any sensitive info, but it would be good to know if it exists in the first place, and whether the files in there are looking as expected.

**Comment by DEVTomatoCake** [comment]
Folder structure changed, in case you aren't aware yet @davidbmaier:
```
📂 activity
   📂 analytics
      📄 events-2024-00000-of-00001.json
   📂 tns
      📄 events-2024-00000-of-00001.json
```

There's no `reporting` folder anymore.

**Comment by davidbmaier** [comment]
Hmm gotcha, I only used `/reports` as the fallback for `/analytics` so as long as that's available it shouldn't complain, but maybe there's something else going wrong.
I'll fix it as soon as I get my next package, thanks for letting me know.

**Comment by davidbmaier** [comment]
Should be fixed, I adjusted some of the directory structure-related stuff to adapt to the new formats. Looks like they also changed their channel type IDs, so there were some more issues.
Feel free to reopen if you still see issues with current packages - especially accounts with strict privacy settings might still run into edge cases I haven't been able to test yet, but I'm hopeful it'll work fine.
