### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by itzscorpio** [davidbmaier/discord-recap#26]
Hello, having an issue whenever i try to upload.

![image_2024-12-15_024714395](https://github.com/user-attachments/assets/011cc449-180e-4972-9afb-8d5f4a238cae)

![image](https://github.com/user-attachments/assets/2333aafb-6eb2-4546-b79d-f58d37bfbb57)
![image](https://github.com/user-attachments/assets/2cff5268-cb89-4dc6-bbbc-33b9690535a5)

thanks

**Comment by davidbmaier** [comment]
Not able to reproduce that with my most recent data package but it seems to be related to how the site detects dark mode in the user data - I pushed a quick patch, feel free to give that a try and let me know if that works.

**Comment by itzscorpio** [comment]
such a quick response!!! thank you that worked well...
