### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Banalian** [davidbmaier/discord-recap#3]
When navigating through my package (in the different dms), i have some big latency to open some dm's stats. I tried to go back using Chrome instead of the button since it was not loading the pages, until i got this error.

![image](https://user-images.githubusercontent.com/64379456/148702653-71dc148d-df3f-45c8-9c59-dfbec5b7b5a3.png)

**Comment by davidbmaier** [comment]
The site isn't fetching anything, so that must have been a Netlify hiccup I guess?
Don't think that's got anything to do with the site. Feel free to reopen if you can reproduce it consistently.
