### ISSUE TITLE
Annual recap first message not correctly updating every time

### ISSUE THREAD

**Issue by Banalian** [davidbmaier/discord-recap#4]
When in the annual recap, the first annual message works, until you try to go back one year (from 2020 to 2019 for example). The channel is correct but the actual message stays the same.

The change is only correct for the first year change, and after that until you stop going forward i think.

![caMarchePo](https://user-images.githubusercontent.com/64379456/148702834-145bd8d2-15d5-45a2-b346-228ba52c953e.gif)

**Comment by davidbmaier** [comment]
Huh interesting, will check it out.

**Comment by davidbmaier** [comment]
Can't reproduce this at all - I tried to make sure no weird references can get stuck in https://github.com/davidbmaier/discord-recap/commit/e2ce5f7006bfc56c0e3bf32d5c321e5e30ebc463 but I'm not sure what's going on here.

Can I get some more specifics? Which browser does this happen in, do you see any errors in the console?

**Comment by Banalian** [comment]
This happens in Chrome's current version (97.0.4692.71 64 bits) i checked but there's no errors in the console, except one at the start that i suppose is unrelated `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

I tried with another package and it was even worse, it never changed the message, it kept the last one

I might have an idea to what is causing it : It seems to break whenever the message starts to contain an emoji ( :D in my example ), on my package, i manage to have the correct message with another year, but the moment i choose a year with an emoji, it breaks and never change the message again

A friend tried on firefox and doesn't have any trouble, definitively a chrome error i think
I tried on Opera Gx, and edge, with no trouble

**Comment by Banalian** [comment]
I think we can close the issue, i found the trouble, my Tweenmoji extension seems to be breaking it, no idea why it's the case.

**Comment by davidbmaier** [comment]
Huh, interesting. Maybe it's interfering with re-renders since it's trying to change content dynamically.
Good to hear it's not related to the site though 😅
